### ISSUE TITLE
Update README example config - remove CircularBlobAccess

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildbarn/bb-remote-asset#17]
The example config quoted in the README uses CircularBlobAccess (the keyword 'circular').

CircularBlobAccess has been [removed from bb-storage](https://github.com/buildbarn/bb-storage/commit/e6de4f65c1e35ca625b7e1f2dffe9c14833f333e). And bb-remote-access has now been updated to include those changes. The README ought to be updated to use LocalBlobAccess.

**Comment by Cynical-Optimist** [comment]
If it helps, this was prompted by an issue we're having on the remote-apis-testing project:

https://gitlab.com/remote-apis-testing/remote-apis-testing/-/issues/111

**Comment by EdSchouten** [comment]
Hey there!

This part of the config:
```
    circular: {
      directory: '/storage',
      offsetFileSizeBytes: 1024 * 1024,
      offsetCacheSize: 1000,
      dataFileSizeBytes: 100 * 1024 * 1024,
      dataAllocationChunkSizeBytes: 1048576,
      instances: ['remote-execution'],
    },
```
can be replaced with:
```
    'local': {
      keyLocationMapOnBlockDevice: {
        file: {
          path: '/storage/key_location_map',
          sizeBytes: 1024 * 1024,
        },
      },
      keyLocationMapMaximumGetAttempts: 8,
      keyLocationMapMaximumPutAttempts: 32,
      oldBlocks: 8,
      currentBlocks: 24,
      newBlocks: 3,
      blocksOnBlockDevice: {
        source: {
          file: {
            path: '/storage/blocks',
            sizeBytes: 100 * 1024 * 1024,
          },
        },
        spareBlocks: 3,
      },
      // Add this chunk if you also want it to be persistent across restarts. If no persistency is needed, just omit this.
      persistent: {
        stateDirectoryPath: '/storage/persistent_state',
        minimumEpochInterval: '5m',
      },
    },
```
And this part:
```
  httpListenAddress: ':7982',
```
Needs to be replaced with:
```
global: { diagnosticsHttpListenAddress: ':7982' },
```

**Comment by Cynical-Optimist** [comment]
Thanks @EdSchouten, I've tested that on Remote-Testing-APIs, and it works perfectly. That was a really big help?

re updating the README, I assume the same changes would apply there? (But with "/storage" changed to "/storage-asset" and "remote-execution" changed to "foo", as in the current README.)

What about the undertext though? The paragraph that starts "In the example above, the daemon is configured to store asset references within a disk backed circular storage backend.". The part about the circular storage backend obviously ought to be changed to something else. Does the rest need to be changed too?
