### ISSUE TITLE
Sort out configuration

### ISSUE THREAD

**Issue by sdclarke** [buildbarn/bb-remote-asset#21]
Currently the configuration of the server is somewhat complicated and ambiguous, there are fields which end up unused and use cases which may not be possible to specify.

Specifically the configuration of the CAS needs some attention as it can be specified in the httpFetcher config but will not do anything, meaning that currently an assetCache config must be present.

Perhaps another option is needed under the assetCache to simply specify a CAS and have no asset caching.

**Comment by tomcoldrick-ct** [comment]
Closed by #22
