### ISSUE TITLE
Use AC for asset storage

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-remote-asset#3]
Currently assets are stored into a blob access using a custom `BlobAccessCreator` which is less than ideal and introduces a wide range of restrictions on how we can use the blob access interface without additional boiler plate code.

Going forward, we should aim to standardise on using the action cache to store our assets by constructing [Actions](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L388-L436) from [PushBlob](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L370-L401)/[PushDirectory](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L409-L441) requests and also when performing a [remote fetch](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L90-L91).

When fetching, we can create an Action per URI and perform a [GetActionResult](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L151-L153) request for each to retrieve the blob or directory digest required to form a [FetchBlob](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L208-L235)/[FetchDirectory](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L287-L315) Response.

**Comment by EdSchouten** [comment]
I would suggest not creating one Action per URI, but for all URIs combined. That way a single GetActionResult suffices.

**Comment by tomcoldrick-ct** [comment]
I think we have a trade off to make there - it's more efficient in typical cases to use a single GetActionResult and a single Execute request, but it also means we're caching based upon the _set_ of URIs which are sent in the request, rather than on the individual URI. I could see this being an issue in a case like a new source mirror being set up, which adds a URI to every request and invalidates the cache for all sources. Given this kind of thing _should_ be rare, it may be worthwhile to suffer this occasional cache invalidation for the optimisation of requests in the typical case.

If we use multiple URIs in a single Action, we'll also have to store the matched URI somewhere as the matched URI is required in the Fetch*Response [by the spec](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/asset/v1/remote_asset.proto#L221-L223).

**Comment by EdSchouten** [comment]
![0fc](https://user-images.githubusercontent.com/736085/91544103-8900a400-e91f-11ea-9f9a-9741baaf190b.gif)

Alternative: we could create AC entries both for an individual URL being fetched correctly, and an AC entry that then ties it all together for multiple URLs. That way you have the advantage of being able to call GetActionResult() just once in the common cached case, while falling back to multiple calls if the list of mirrors is changed.

**Comment by tomcoldrick-ct** [comment]
https://github.com/bazelbuild/remote-apis/issues/144 may have implications on this in the future, but I don't think we need to worry about it at the moment.

**Comment by tomcoldrick-ct** [comment]
I've had a little bit of a play around with this concept at https://github.com/tomcoldrick-ct/bb-remote-asset/tree/coldtom/ac-experiment, but I haven't managed to get it working at all yet.

**Comment by sdclarke** [comment]
Presumably we need some way of storing qualifiers in the action message for this to work correctly? I was considering having them as part of the arguments for the command, at the end preceded by `#`, to produce something like this:
```
Command {
    Arguments: []string{uri1, uri2, "#", qualifier1, qualifier2},
}
```
where qualifier1 and qualifier2 are the qualifiers formatted as `name:value`. This would mean that in future if the command is to be converted into something which could actually be executed the qualifiers would still be able to exist in the action.

Another option would be using the command's `EnvironmentVariables` field, although I'm not sure if that's a great idea given that it would affect the environment if the command were to be adapted to be runnable as mentioned above.

Does anyone have any thoughts on how best to tackle this?

**Comment by EdSchouten** [comment]
You could create a fictive input root that contains a file with a Protobuf

**Comment by Qinusty** [comment]
https://github.com/buildbarn/bb-remote-asset/pull/16 was merged to resolve this issue.
