### ISSUE TITLE
Configuration/Doc Updates

### ISSUE THREAD

**Issue by pseymournutanix** [buildbarn/bb-remote-asset#32]
https://github.com/buildbarn/bb-remote-asset/pkgs/container/bb-remote-asset

Seems to have an old configuration using that and the latest image I get 
 
```
2023/12/04 17:25:46 Fatal error: rpc error: code = Unimplemented desc = Failed to create asset store and CAS: NewBlockListGrowthPolicy unimplemeted for assetBlobAccessCreator
```

And I am unsure on how to configure, any help would be appreciated.

**Comment by tomcoldrick-ct** [comment]
Sorry for the delay in getting back to this, the issue is nothing to do with your configuration but an unimplemented API in bb-remote-asset.  #35 implements the missing method and should stop this error.
