### ISSUE TITLE
CI in main has failed, so latest container was not pushed to the registry

### ISSUE THREAD

**Issue by jjardon** [buildbarn/bb-remote-asset#37]
See https://github.com/buildbarn/bb-remote-asset/actions/runs/8229689658/job/22501380663

CC: @tomcoldrick-ct

**Comment by jjardon** [comment]
This seems to be fixed now: https://github.com/buildbarn/bb-remote-asset/actions/runs/9365740116/job/25781595283

**Comment by tomcoldrick-ct** [comment]
Looks like it was a transient network issue?  Checksum of a remote file was incorrect, so I'm guessing we actually got an HTTP 5XX error or similar.
